// protoc --proto_path=. --micro_out=. --go_out=:. partner.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: partner.proto

package partner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactModule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tel     string `protobuf:"bytes,1,opt,name=tel,proto3" json:"tel,omitempty"`
	Phone   string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email   string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ContactModule) Reset() {
	*x = ContactModule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactModule) ProtoMessage() {}

func (x *ContactModule) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactModule.ProtoReflect.Descriptor instead.
func (*ContactModule) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{0}
}

func (x *ContactModule) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *ContactModule) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ContactModule) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactModule) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CustomerModule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgeRange string `protobuf:"bytes,1,opt,name=ageRange,proto3" json:"ageRange,omitempty"`
	Sex      string `protobuf:"bytes,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Region   string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *CustomerModule) Reset() {
	*x = CustomerModule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerModule) ProtoMessage() {}

func (x *CustomerModule) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerModule.ProtoReflect.Descriptor instead.
func (*CustomerModule) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerModule) GetAgeRange() string {
	if x != nil {
		return x.AgeRange
	}
	return ""
}

func (x *CustomerModule) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *CustomerModule) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type SocialMediaModule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instagram string `protobuf:"bytes,1,opt,name=instagram,proto3" json:"instagram,omitempty"`
	Facebook  string `protobuf:"bytes,2,opt,name=facebook,proto3" json:"facebook,omitempty"`
	Threads   string `protobuf:"bytes,3,opt,name=threads,proto3" json:"threads,omitempty"`
	Twitter   string `protobuf:"bytes,4,opt,name=twitter,proto3" json:"twitter,omitempty"`
}

func (x *SocialMediaModule) Reset() {
	*x = SocialMediaModule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialMediaModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMediaModule) ProtoMessage() {}

func (x *SocialMediaModule) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMediaModule.ProtoReflect.Descriptor instead.
func (*SocialMediaModule) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{2}
}

func (x *SocialMediaModule) GetInstagram() string {
	if x != nil {
		return x.Instagram
	}
	return ""
}

func (x *SocialMediaModule) GetFacebook() string {
	if x != nil {
		return x.Facebook
	}
	return ""
}

func (x *SocialMediaModule) GetThreads() string {
	if x != nil {
		return x.Threads
	}
	return ""
}

func (x *SocialMediaModule) GetTwitter() string {
	if x != nil {
		return x.Twitter
	}
	return ""
}

type PartnerModule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrandName      string             `protobuf:"bytes,1,opt,name=brandName,proto3" json:"brandName,omitempty"`
	PersonInCharge string             `protobuf:"bytes,2,opt,name=personInCharge,proto3" json:"personInCharge,omitempty"`
	CompanyName    string             `protobuf:"bytes,3,opt,name=companyName,proto3" json:"companyName,omitempty"`
	ContactPerson  string             `protobuf:"bytes,8,opt,name=contactPerson,proto3" json:"contactPerson,omitempty"`
	DeleteStatus   bool               `protobuf:"varint,4,opt,name=deleteStatus,proto3" json:"deleteStatus,omitempty"`
	Contact        *ContactModule     `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	Customer       *CustomerModule    `protobuf:"bytes,6,opt,name=customer,proto3" json:"customer,omitempty"`
	SocialMedia    *SocialMediaModule `protobuf:"bytes,7,opt,name=socialMedia,proto3" json:"socialMedia,omitempty"`
}

func (x *PartnerModule) Reset() {
	*x = PartnerModule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnerModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerModule) ProtoMessage() {}

func (x *PartnerModule) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerModule.ProtoReflect.Descriptor instead.
func (*PartnerModule) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{3}
}

func (x *PartnerModule) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *PartnerModule) GetPersonInCharge() string {
	if x != nil {
		return x.PersonInCharge
	}
	return ""
}

func (x *PartnerModule) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *PartnerModule) GetContactPerson() string {
	if x != nil {
		return x.ContactPerson
	}
	return ""
}

func (x *PartnerModule) GetDeleteStatus() bool {
	if x != nil {
		return x.DeleteStatus
	}
	return false
}

func (x *PartnerModule) GetContact() *ContactModule {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *PartnerModule) GetCustomer() *CustomerModule {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *PartnerModule) GetSocialMedia() *SocialMediaModule {
	if x != nil {
		return x.SocialMedia
	}
	return nil
}

type GetPartnerByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrandName string `protobuf:"bytes,1,opt,name=brandName,proto3" json:"brandName,omitempty"`
}

func (x *GetPartnerByNameRequest) Reset() {
	*x = GetPartnerByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartnerByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartnerByNameRequest) ProtoMessage() {}

func (x *GetPartnerByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartnerByNameRequest.ProtoReflect.Descriptor instead.
func (*GetPartnerByNameRequest) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{4}
}

func (x *GetPartnerByNameRequest) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

type GetPartnerByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode int32  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
}

func (x *GetPartnerByNameResponse) Reset() {
	*x = GetPartnerByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartnerByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartnerByNameResponse) ProtoMessage() {}

func (x *GetPartnerByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartnerByNameResponse.ProtoReflect.Descriptor instead.
func (*GetPartnerByNameResponse) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{5}
}

func (x *GetPartnerByNameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPartnerByNameResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type GetPartnerByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPartnerByIdRequest) Reset() {
	*x = GetPartnerByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartnerByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartnerByIdRequest) ProtoMessage() {}

func (x *GetPartnerByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartnerByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPartnerByIdRequest) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{6}
}

func (x *GetPartnerByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPartnerByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    string           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode int32            `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Partner    *structpb.Struct `protobuf:"bytes,3,opt,name=partner,proto3" json:"partner,omitempty"`
}

func (x *GetPartnerByIdResponse) Reset() {
	*x = GetPartnerByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartnerByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartnerByIdResponse) ProtoMessage() {}

func (x *GetPartnerByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartnerByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPartnerByIdResponse) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{7}
}

func (x *GetPartnerByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPartnerByIdResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetPartnerByIdResponse) GetPartner() *structpb.Struct {
	if x != nil {
		return x.Partner
	}
	return nil
}

type CreatePartnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Partner *PartnerModule `protobuf:"bytes,1,opt,name=partner,proto3" json:"partner,omitempty"`
}

func (x *CreatePartnerRequest) Reset() {
	*x = CreatePartnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePartnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartnerRequest) ProtoMessage() {}

func (x *CreatePartnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartnerRequest.ProtoReflect.Descriptor instead.
func (*CreatePartnerRequest) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePartnerRequest) GetPartner() *PartnerModule {
	if x != nil {
		return x.Partner
	}
	return nil
}

type CreatePartnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode int32  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
}

func (x *CreatePartnerResponse) Reset() {
	*x = CreatePartnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePartnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartnerResponse) ProtoMessage() {}

func (x *CreatePartnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartnerResponse.ProtoReflect.Descriptor instead.
func (*CreatePartnerResponse) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePartnerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreatePartnerResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type UpdatePartnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Partner *PartnerModule `protobuf:"bytes,2,opt,name=partner,proto3" json:"partner,omitempty"`
}

func (x *UpdatePartnerRequest) Reset() {
	*x = UpdatePartnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePartnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartnerRequest) ProtoMessage() {}

func (x *UpdatePartnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartnerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePartnerRequest) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePartnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePartnerRequest) GetPartner() *PartnerModule {
	if x != nil {
		return x.Partner
	}
	return nil
}

type UpdatePartnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode int32  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
}

func (x *UpdatePartnerResponse) Reset() {
	*x = UpdatePartnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePartnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartnerResponse) ProtoMessage() {}

func (x *UpdatePartnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartnerResponse.ProtoReflect.Descriptor instead.
func (*UpdatePartnerResponse) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePartnerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePartnerResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type DeletePartnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePartnerRequest) Reset() {
	*x = DeletePartnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePartnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePartnerRequest) ProtoMessage() {}

func (x *DeletePartnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePartnerRequest.ProtoReflect.Descriptor instead.
func (*DeletePartnerRequest) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{12}
}

func (x *DeletePartnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePartnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode int32  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
}

func (x *DeletePartnerResponse) Reset() {
	*x = DeletePartnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePartnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePartnerResponse) ProtoMessage() {}

func (x *DeletePartnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePartnerResponse.ProtoReflect.Descriptor instead.
func (*DeletePartnerResponse) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{13}
}

func (x *DeletePartnerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeletePartnerResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type GetPartnersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPartnersRequest) Reset() {
	*x = GetPartnersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartnersRequest) ProtoMessage() {}

func (x *GetPartnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartnersRequest.ProtoReflect.Descriptor instead.
func (*GetPartnersRequest) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{14}
}

type GetPartnersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Partner []*structpb.Struct `protobuf:"bytes,1,rep,name=partner,proto3" json:"partner,omitempty"`
}

func (x *GetPartnersResponse) Reset() {
	*x = GetPartnersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartnersResponse) ProtoMessage() {}

func (x *GetPartnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartnersResponse.ProtoReflect.Descriptor instead.
func (*GetPartnersResponse) Descriptor() ([]byte, []int) {
	return file_partner_proto_rawDescGZIP(), []int{15}
}

func (x *GetPartnersResponse) GetPartner() []*structpb.Struct {
	if x != nil {
		return x.Partner
	}
	return nil
}

var File_partner_proto protoreflect.FileDescriptor

var file_partner_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a,
	0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x56, 0x0a, 0x0e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x81,
	0x01, 0x0a, 0x11, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72,
	0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x77, 0x69, 0x74,
	0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x77, 0x69, 0x74, 0x74,
	0x65, 0x72, 0x22, 0xce, 0x02, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e, 0x43, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x49, 0x6e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x12, 0x2b, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x34, 0x0a,
	0x0b, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x0b, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x22, 0x37, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65,
	0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x54, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x31, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74,
	0x6e, 0x65, 0x72, 0x22, 0x40, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x70,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x22, 0x51, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x50, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x28, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x22, 0x51, 0x0a, 0x15, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x26, 0x0a,
	0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x51, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52,
	0x07, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x32, 0x9b, 0x03, 0x0a, 0x07, 0x70, 0x61, 0x72,
	0x74, 0x6e, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e,
	0x65, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x42,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x49,
	0x64, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x70, 0x61, 0x72, 0x74,
	0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_partner_proto_rawDescOnce sync.Once
	file_partner_proto_rawDescData = file_partner_proto_rawDesc
)

func file_partner_proto_rawDescGZIP() []byte {
	file_partner_proto_rawDescOnce.Do(func() {
		file_partner_proto_rawDescData = protoimpl.X.CompressGZIP(file_partner_proto_rawDescData)
	})
	return file_partner_proto_rawDescData
}

var file_partner_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_partner_proto_goTypes = []any{
	(*ContactModule)(nil),            // 0: ContactModule
	(*CustomerModule)(nil),           // 1: CustomerModule
	(*SocialMediaModule)(nil),        // 2: SocialMediaModule
	(*PartnerModule)(nil),            // 3: PartnerModule
	(*GetPartnerByNameRequest)(nil),  // 4: GetPartnerByNameRequest
	(*GetPartnerByNameResponse)(nil), // 5: GetPartnerByNameResponse
	(*GetPartnerByIdRequest)(nil),    // 6: GetPartnerByIdRequest
	(*GetPartnerByIdResponse)(nil),   // 7: GetPartnerByIdResponse
	(*CreatePartnerRequest)(nil),     // 8: CreatePartnerRequest
	(*CreatePartnerResponse)(nil),    // 9: CreatePartnerResponse
	(*UpdatePartnerRequest)(nil),     // 10: UpdatePartnerRequest
	(*UpdatePartnerResponse)(nil),    // 11: UpdatePartnerResponse
	(*DeletePartnerRequest)(nil),     // 12: DeletePartnerRequest
	(*DeletePartnerResponse)(nil),    // 13: DeletePartnerResponse
	(*GetPartnersRequest)(nil),       // 14: GetPartnersRequest
	(*GetPartnersResponse)(nil),      // 15: GetPartnersResponse
	(*structpb.Struct)(nil),          // 16: google.protobuf.Struct
}
var file_partner_proto_depIdxs = []int32{
	0,  // 0: PartnerModule.contact:type_name -> ContactModule
	1,  // 1: PartnerModule.customer:type_name -> CustomerModule
	2,  // 2: PartnerModule.socialMedia:type_name -> SocialMediaModule
	16, // 3: GetPartnerByIdResponse.partner:type_name -> google.protobuf.Struct
	3,  // 4: CreatePartnerRequest.partner:type_name -> PartnerModule
	3,  // 5: UpdatePartnerRequest.partner:type_name -> PartnerModule
	16, // 6: GetPartnersResponse.partner:type_name -> google.protobuf.Struct
	4,  // 7: partner.GetPartnerByName:input_type -> GetPartnerByNameRequest
	6,  // 8: partner.GetPartnerById:input_type -> GetPartnerByIdRequest
	8,  // 9: partner.CreatePartner:input_type -> CreatePartnerRequest
	10, // 10: partner.UpdatePartner:input_type -> UpdatePartnerRequest
	12, // 11: partner.DeletePartner:input_type -> DeletePartnerRequest
	14, // 12: partner.GetPartners:input_type -> GetPartnersRequest
	5,  // 13: partner.GetPartnerByName:output_type -> GetPartnerByNameResponse
	7,  // 14: partner.GetPartnerById:output_type -> GetPartnerByIdResponse
	9,  // 15: partner.CreatePartner:output_type -> CreatePartnerResponse
	11, // 16: partner.UpdatePartner:output_type -> UpdatePartnerResponse
	13, // 17: partner.DeletePartner:output_type -> DeletePartnerResponse
	15, // 18: partner.GetPartners:output_type -> GetPartnersResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_partner_proto_init() }
func file_partner_proto_init() {
	if File_partner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_partner_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ContactModule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CustomerModule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SocialMediaModule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PartnerModule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetPartnerByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetPartnerByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetPartnerByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetPartnerByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePartnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePartnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePartnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePartnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DeletePartnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*DeletePartnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*GetPartnersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GetPartnersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_partner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_partner_proto_goTypes,
		DependencyIndexes: file_partner_proto_depIdxs,
		MessageInfos:      file_partner_proto_msgTypes,
	}.Build()
	File_partner_proto = out.File
	file_partner_proto_rawDesc = nil
	file_partner_proto_goTypes = nil
	file_partner_proto_depIdxs = nil
}
