definitions:
  activity.CreateActivityResponse:
    properties:
      message:
        type: string
      statusCode:
        type: integer
      success:
        type: boolean
    type: object
  activity.DeleteActivityResponse:
    properties:
      message:
        type: string
      statusCode:
        type: integer
      success:
        type: boolean
    type: object
  activity.UpdateActivityResponse:
    properties:
      message:
        type: string
      statusCode:
        type: integer
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: 包含所有 api 的用法.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Prizoo Api Document
  version: "1.0"
paths:
  /activity:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"data": "活動內容"}'
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      summary: 獲取所有活動的資料
      tags:
      - Activity
    post:
      parameters:
      - description: 活動名稱
        in: formData
        name: title
        required: true
        type: string
      - description: 活動細節介紹
        in: formData
        name: detial
        required: true
        type: string
      - description: 活動開始時間(unix time stamp)
        in: formData
        name: startTime
        required: true
        type: string
      - description: 活動結束時間(unix time stamp)
        in: formData
        name: endTime
        required: true
        type: string
      - description: 提供活動的廠商名稱
        in: formData
        name: partner
        required: true
        type: string
      - description: 獎品名稱
        in: formData
        name: prizeName
        required: true
        type: string
      - description: 獎品的圖片
        in: formData
        name: image
        required: true
        type: file
      - description: 加碼的獎品名稱
        in: formData
        name: addPrizeName
        required: true
        type: string
      - description: 加碼獎品的圖片
        in: formData
        name: addPrizeImage
        required: true
        type: file
      - description: 多少票券加入之後開啟加碼
        in: formData
        name: addPrizeTicketAmount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/activity.CreateActivityResponse'
        "400":
          description: 輸入錯誤
          schema:
            $ref: '#/definitions/activity.CreateActivityResponse'
        "500":
          description: 系統錯誤
          schema:
            $ref: '#/definitions/activity.CreateActivityResponse'
      summary: 新建一個活動
      tags:
      - Activity
  /activity/{id}:
    delete:
      parameters:
      - description: 活動 id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/activity.DeleteActivityResponse'
        "400":
          description: 錯誤的 id
          schema:
            $ref: '#/definitions/activity.DeleteActivityResponse'
        "500":
          description: 系統錯誤
          schema:
            $ref: '#/definitions/activity.DeleteActivityResponse'
      summary: 刪除特定 id 的活動
      tags:
      - Activity
    get:
      parameters:
      - description: 活動 id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"data": "活動內容"}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: '{"message": "錯誤訊息"}'
          schema:
            additionalProperties: true
            type: object
        "500":
          description: '{"message": "獲取失敗，請重試"}'
          schema:
            additionalProperties: true
            type: object
      summary: 獲取特定 id 的活動
      tags:
      - Activity
    patch:
      parameters:
      - description: 要更新的活動 id
        in: path
        name: id
        required: true
        type: string
      - description: 活動名稱
        in: formData
        name: title
        required: true
        type: string
      - description: 活動細節介紹
        in: formData
        name: detial
        required: true
        type: string
      - description: 活動開始時間(unix time stamp)
        in: formData
        name: startTime
        required: true
        type: string
      - description: 活動結束時間(unix time stamp)
        in: formData
        name: endTime
        required: true
        type: string
      - description: 提供活動的廠商名稱
        in: formData
        name: partner
        required: true
        type: string
      - description: 獎品名稱
        in: formData
        name: prizeName
        required: true
        type: string
      - description: 獎品的圖片
        in: formData
        name: image
        required: true
        type: file
      - description: 加碼的獎品名稱
        in: formData
        name: addPrizeName
        required: true
        type: string
      - description: 多少票券加入之後開啟加碼
        in: formData
        name: addPrizeTicketAmount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/activity.UpdateActivityResponse'
        "400":
          description: 錯誤的 id
          schema:
            $ref: '#/definitions/activity.UpdateActivityResponse'
        "500":
          description: 系統錯誤
          schema:
            $ref: '#/definitions/activity.UpdateActivityResponse'
      summary: 更新指定 id 的活動內容
      tags:
      - Activity
  /activity/history/{id}:
    get:
      parameters:
      - description: 要查看的活動 id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"data": "歷史記錄陣列"}'
          schema:
            additionalProperties: true
            type: object
      summary: 查看特定活動 id 的修改歷史記錄
      tags:
      - Activity
swagger: "2.0"
